package br.com.yaw.prime.model;
// Generated Nov 4, 2015 3:58:18 PM by Hibernate Tools 4.0.0


import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Supermercado generated by hbm2java
 */
@Entity
@Table(name = "supermercado")
public class Supermercado implements AbstractEntity {

	private static final long serialVersionUID = 1L;
	
	private Long id;
	private String supermercado;

	public Supermercado() {
	}

	public Supermercado(String supermercado) {
		this.supermercado = supermercado;
	}


	@Id
	@GeneratedValue(strategy = IDENTITY)

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public String getSupermercado() {
		return this.supermercado;
	}

	public void setSupermercado(String supermercado) {
		this.supermercado = supermercado;
	}


}
